# Generated by Django 4.1.2 on 2022-12-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamesartikels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('thumb', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('desc', models.TextField()),
                ('key', models.CharField(max_length=225)),
            ],
        ),
    ]
