# Generated by Django 4.1.3 on 2022-12-13 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artikels", "0002_gamesartikels_idberita"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gamesartikels",
            old_name="idberita",
            new_name="idgames",
        ),
    ]
