# Generated by Django 4.1.3 on 2022-12-13 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artikels", "0003_rename_idberita_gamesartikels_idgames"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamesartikels",
            name="idgames",
        ),
    ]
